# Generated by Django 3.0.2 on 2020-01-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_tracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
