frameworkVersion: "=1.53.0"

# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: skypt

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: imp-python3.7
  namespace: imp-test
  hostname: skypt.dev.hhe.nonprod.imp.sky.com
  ingress:
    class: avi
    additionalAnnotations:
      avi_proxy: '{"virtualservice": {"services": [{"port": 443, "enable_ssl": true}], "east_west_placement": false, "ssl_key_and_certificate_refs": ["/api/sslkeyandcertificate?name=System-Default-Cert"], "ssl_profile_ref": "/api/sslprofile/?name=System-Standard"}}'
  environment:
    - name: skypt_ldapnode
      valueFrom:
        secretKeyRef:
          name: skypt
          key: ldapnode
    - name: skypt_ldapuser
      valueFrom:
        secretKeyRef:
          name: skypt
          key: ldapuser
    - name: skypt_ldappass
      valueFrom:
        secretKeyRef:
          name: skypt
          key: ldappass
    - name: skypt_ldapbase
      valueFrom:
        secretKeyRef:
          name: skypt
          key: ldapbase
    - name: skypt_token
      valueFrom:
        secretKeyRef:
          name: skypt
          key: token
plugins:
  - serverless-kubeless

package:
 exclude:
   - secrets

functions:
  employee-getbyname:
    handler: handler_employee.getByName
    events: 
     - http:
        path: /employee/getbyname
