frameworkVersion: "=1.53.0"

# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: skypt

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: imp-python3.7
  namespace: imp-test
  hostname: skypt.dev.hhe.nonprod.imp.sky.com
  ingress:
    class: avi
    additionalAnnotations:
      avi_proxy: '{"virtualservice": {"services": [{"port": 443, "enable_ssl": true}], "east_west_placement": false, "ssl_key_and_certificate_refs": ["/api/sslkeyandcertificate?name=System-Default-Cert"], "ssl_profile_ref": "/api/sslprofile/?name=System-Standard"}}'
  environment:
    - name: skypt_token
      valueFrom:
        secretKeyRef:
          name: skypt
          key: token
    - name: skypt_dbhost
      valueFrom:
        secretKeyRef:
          name: skypt
          key: dbhost
    - name: skypt_dbdatabase
      valueFrom:
        secretKeyRef:
          name: skypt
          key: dbdatabase
    - name: skypt_dbuser
      valueFrom:
        secretKeyRef:
          name: skypt
          key: dbuser
    - name: skypt_dbpass
      valueFrom:
        secretKeyRef:
          name: skypt
          key: dbpass

plugins:
  - serverless-kubeless

package:
 exclude:
   - docs

functions:

  #  _____                 _                       
  # | ____|_ __ ___  _ __ | | ___  _   _  ___  ___ 
  # |  _| | '_ ` _ \| '_ \| |/ _ \| | | |/ _ \/ _ \
  # | |___| | | | | | |_) | | (_) | |_| |  __/  __/
  # |_____|_| |_| |_| .__/|_|\___/ \__, |\___|\___|
  #                 |_|            |___/   
  skypt-employee-getbyname:
    handler: lib_handler_employee.getByName
    events: 
     - http:
        path: /employee/getbyname
    environment:
      - name: skypt_ldapnode
        valueFrom:
          secretKeyRef:
            name: skypt
            key: ldapnode
      - name: skypt_ldapuser
        valueFrom:
          secretKeyRef:
            name: skypt
            key: ldapuser
      - name: skypt_ldappass
        valueFrom:
          secretKeyRef:
            name: skypt
            key: ldappass
      - name: skypt_ldapbase
        valueFrom:
          secretKeyRef:
            name: skypt
            key: ldapbase

  #  ____            _                    
  # |  _ \ __ _  ___| | ____ _  __ _  ___ 
  # | |_) / _` |/ __| |/ / _` |/ _` |/ _ \
  # |  __/ (_| | (__|   < (_| | (_| |  __/
  # |_|   \__,_|\___|_|\_\__,_|\__, |\___|
  #                            |___/   
  skypt-package-add:
    handler: lib_handler_package.add
    events: 
     - http:
        path: /package/add

  skypt-package-get:
    handler: lib_handler_package.get
    events: 
     - http:
        path: /package/get


  #  _____                 _ _ 
  # | ____|_ __ ___   __ _(_) |
  # |  _| | '_ ` _ \ / _` | | |
  # | |___| | | | | | (_| | | |
  # |_____|_| |_| |_|\__,_|_|_|
  skypt-email-package:
    handler: lib_handler_email.package
    events: 
     - http:
        path: /email/package