import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

import Screenshot from './src/Screenshot'
import Employee from './src/Employee'
import Confirmation from './src/Confirmation'

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={Screenshot} />
        <Stack.Screen name="Employee" component={Employee} />
        <Stack.Screen name="Confirmation" component={Confirmation}
        // initialParams={
        //   {
        //     "employee": {
        //       "cn": "Martin, Frans",
        //       "email": "@sky.uk",
        //       "mobile": "+",
        //       "user": ""
        //     },
        //     "params": {
        //       "base64": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAEsAZADASIAAhEBAxEB/8QAGQABAQEBAQEAAAAAAAAAAAAAAAECAwQG/8QAKhABAQABAQYFBAMBAAAAAAAAAAECEQMTMUFRcSEyQoHBBBJhkSJSobH/xAAWAQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAEQH/2gAMAwEAAhEDEQA/APj1QVhYsReYLFRQVWVBbxndceHvf+s3kuPAGliRRFIkUFlVCKKqAKnqnah6vYFAAQAEAEZy5d2mcuXcFRUBlFAZqVaiKzUarIJWa0lFZSrUBBUqKgAFRUAAFAAdd5i1M8escASPTLLzWPKsys4WwI9Q828z/s1NtlOlVI9CuE2954tT6jHnKEdbxhj5WcdpjnlJjxax8s7CNRUAaEBGl1ZVRRAGk53sJPNe0+QaEAURNQUSgDOXGd1ZvHHv8AtRalQRKqAlRagrNRUBKipRUqVagIlVKgItQURUAAFAAAAAAAANXSbWc9nhfZzAd9lljln/ABwmHhyrtj5Me0efYeFyv4d8fLOys60rOq6iLFQEaIhqDRompqo0zPNfb5NScaCmqGqCiCgJqAJeM7qzfNAVAQEEoJUWoKlTktZ5AVmrUooi1ARKqIpUVAEVAABQAAAAAAAAAHTZcM+z0R5sMpjjlLzngs22f4E3HpHnm3s44ytT6ic8f9VI7jjNvh0rU22zvq09hI6jE2mF9U/bUsvCygqoCKmviapONBoQ1BREBRNQFZvmna/Cp6p2vwKqFBEqKlFSoqAlScFZnCAVKqUVEVKCAVFQKAAAgAAAoAAAAAAAAAAAAAAACzKzhbGptc56qwA6b7addfZd/n0jkCR2n1F54z2rU+onPGvOBMenf4XrGt7hfU8gEeveYf2n7a16PECR7U5ztfh5JllOGV/a7zPXX7qpHqHmm1z66+yzbZdIEd0ct91x/wBN7OlCOiM7zH8n349Qi3ghrNOM/ZyAqFSgJVQEARRFQAAEAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANaut6oAv3U1qALqaoAupqgCiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANZ4zHOzHKZycMpzZAAAAAAAAAAAAAAAAAF8NEAAAAAAAAF1BBdb1qAAus008dQQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALL9tlnJAHom2k4WztE3011+7LXq4Akdstrc7pvLJ+3PKYzhbfZkFAAAAAAAAAAAACAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF0QBdE8AA8AANTUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/Z",
        //       "deviceOrientation": 1,
        //       "height": 300,
        //       "pictureOrientation": 1,
        //       "width": 400
        //     }
        //   }
        // }
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
